### ISSUE TITLE
Lab1 Comments

### ISSUE THREAD

**Issue by xrem** [SliceOfKekus/OOP#1]
Возвращаемое значение не используется, ты всегда выводишь в консоль строчки ;)
https://github.com/SliceOfKekus/OOP/blob/abcae7281ae149c5dda9645eb25ca6e8a80a7c43/Lab1/parser-ini/IniFileParser.cs#L146-L157

Вместо
https://github.com/SliceOfKekus/OOP/blob/abcae7281ae149c5dda9645eb25ca6e8a80a7c43/Lab1/parser-ini/IniFileParser.cs#L18-L20
Можно использовать Diсtionary.TryGetValue ;)

Один файл = один класс, не два
https://github.com/SliceOfKekus/OOP/blob/abcae7281ae149c5dda9645eb25ca6e8a80a7c43/Lab1/parser-ini/IniFileParser.cs#L36

**Comment by SliceOfKekus** [comment]
Fixed.
